server:
  port: 8101

spring:
  application:
    name: cloud-zuoye-service

#  redis:
#    port: 6379
#    host: 192.168.254.91

  devtools:
    restart:
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinganxiaoyuan2.0?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
